# Generated by Django 5.0.1 on 2025-07-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_enhanced_fight_statistics"),
    ]

    operations = [
        migrations.AddField(
            model_name="scorecard",
            name="json_data",
            field=models.TextField(
                blank=True, help_text="Paste JSON data here to import scorecard"
            ),
        ),
        migrations.AlterField(
            model_name="scorecard",
            name="fighter1_score",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="scorecard",
            name="fighter2_score",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="scorecard",
            name="round_scores",
            field=models.JSONField(
                default=dict, help_text="Round-by-round scores as array"
            ),
        ),
    ]
