# Generated by Django 5.0.1 on 2025-07-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_scorecard_json_data_alter_scorecard_fighter1_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fightstatistics",
            name="json_data",
            field=models.TextField(
                blank=True, help_text="Paste JSON data here to import fight statistics"
            ),
        ),
    ]
