# Generated by Django 5.0.1 on 2025-07-29 21:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_fightstatistics_json_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="FightStoryline",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "headline",
                    models.CharField(
                        help_text="Main headline for the fight storyline",
                        max_length=255,
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        help_text="Brief summary of the fight's significance"
                    ),
                ),
                (
                    "fighter1_background",
                    models.TextField(
                        blank=True,
                        help_text="Fighter 1's career background and journey to this fight",
                    ),
                ),
                (
                    "fighter1_stakes",
                    models.TextField(
                        blank=True, help_text="What's at stake for Fighter 1"
                    ),
                ),
                (
                    "fighter1_keys_to_victory",
                    models.TextField(
                        blank=True, help_text="Fighter 1's keys to victory"
                    ),
                ),
                (
                    "fighter2_background",
                    models.TextField(
                        blank=True,
                        help_text="Fighter 2's career background and journey to this fight",
                    ),
                ),
                (
                    "fighter2_stakes",
                    models.TextField(
                        blank=True, help_text="What's at stake for Fighter 2"
                    ),
                ),
                (
                    "fighter2_keys_to_victory",
                    models.TextField(
                        blank=True, help_text="Fighter 2's keys to victory"
                    ),
                ),
                (
                    "rivalry_history",
                    models.TextField(
                        blank=True, help_text="History and beef between the fighters"
                    ),
                ),
                (
                    "title_implications",
                    models.TextField(
                        blank=True, help_text="Championship or ranking implications"
                    ),
                ),
                (
                    "historical_significance",
                    models.TextField(
                        blank=True, help_text="Historical context and significance"
                    ),
                ),
                (
                    "key_facts",
                    models.JSONField(
                        blank=True, default=list, help_text="Key facts and statistics"
                    ),
                ),
                (
                    "expert_predictions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Expert predictions and analysis",
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True,
                        help_text="Author/Editor of the storyline",
                        max_length=100,
                    ),
                ),
                ("publication_date", models.DateTimeField(blank=True, null=True)),
                (
                    "featured_image_url",
                    models.URLField(
                        blank=True, help_text="Main image for the storyline"
                    ),
                ),
                (
                    "json_data",
                    models.TextField(
                        blank=True,
                        help_text="Paste JSON data here to import storyline content",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fight",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storyline",
                        to="events.fight",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fight Storyline",
                "verbose_name_plural": "Fight Storylines",
                "db_table": "fight_storylines",
                "indexes": [
                    models.Index(fields=["fight"], name="idx_storylines_fight"),
                    models.Index(
                        fields=["publication_date"], name="idx_storylines_pub_date"
                    ),
                ],
            },
        ),
    ]
