# Generated by Django 5.0.1 on 2025-07-30 18:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0006_add_fight_storyline"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventNameVariation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name_variation",
                    models.CharField(
                        help_text="e.g., 'UFC 300', 'UFC 300: Pereira vs. Hill', 'UFC 300 - Pereira vs. Hill'",
                        max_length=255,
                    ),
                ),
                (
                    "variation_type",
                    models.CharField(
                        choices=[
                            ("full", "Full Name Variation"),
                            ("numbered", "Numbered Format"),
                            ("main_event", "Main Event Format"),
                            ("abbreviated", "Abbreviated Format"),
                            ("alternative", "Alternative Format"),
                        ],
                        default="alternative",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Where this variation was found (e.g., 'Wikipedia', 'UFC.com')",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="name_variations",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Name Variation",
                "verbose_name_plural": "Event Name Variations",
                "db_table": "event_name_variations",
                "indexes": [
                    models.Index(fields=["name_variation"], name="idx_event_name_var"),
                    models.Index(fields=["event"], name="idx_event_name_var_event"),
                ],
                "unique_together": {("event", "name_variation")},
            },
        ),
    ]
