# Generated by Django 5.0.1 on 2025-07-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0007_add_event_name_variations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fight",
            name="ending_time",
            field=models.CharField(
                blank=True,
                help_text="Time format: MM:SS (supports long durations)",
                max_length=15,
            ),
        ),
    ]
