# Generated by Django 5.0.1 on 2025-07-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0008_increase_ending_time_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="fight",
            name="fight_section",
            field=models.CharField(
                blank=True,
                help_text="Fight section (e.g., 'Main Card', 'Preliminaries', 'Quarter Finals', 'Final')",
                max_length=100,
            ),
        ),
    ]
