# Generated by Django 5.0.1 on 2025-07-31 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0009_add_fight_section_field"),
        ("organizations", "0002_make_weight_limits_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="last_processed_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp of last processing attempt", null=True
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="last_processing_error",
            field=models.TextField(
                blank=True, help_text="Last error message from processing attempt"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="processing_attempts",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of processing attempts made"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("discovered", "Discovered"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="discovered",
                help_text="Status of Wikipedia scraping and data processing",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["processing_status"], name="idx_events_processing_status"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["processing_status", "-date"], name="idx_events_processing_date"
            ),
        ),
    ]
