services:
  # Django application
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ENVIRONMENT=development
      - DEBUG=True
      - SECRET_KEY=django-insecure-dev-key-change-in-production-please
      - DB_NAME=mma_database
      - DB_USER=mma_user
      - DB_PASSWORD=mma_password
      - DB_HOST=postgres
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/1
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    networks:
      - mma-network
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
  
  # Celery worker for background tasks
  celery:
    build: .
    environment:
      - DJANGO_ENVIRONMENT=development
      - DEBUG=True
      - SECRET_KEY=django-insecure-dev-key-change-in-production-please
      - DB_NAME=mma_database
      - DB_USER=mma_user
      - DB_PASSWORD=mma_password
      - DB_HOST=postgres
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    networks:
      - mma-network
    command: ["celery", "-A", "mma_backend", "worker", "--loglevel=info"]
  
  # Celery beat for scheduled tasks
  celery-beat:
    build: .
    environment:
      - DJANGO_ENVIRONMENT=development
      - DEBUG=True
      - SECRET_KEY=django-insecure-dev-key-change-in-production-please
      - DB_NAME=mma_database
      - DB_USER=mma_user
      - DB_PASSWORD=mma_password
      - DB_HOST=postgres
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    networks:
      - mma-network
    command: ["celery", "-A", "mma_backend", "beat", "--loglevel=info"]

  # PostgreSQL database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: mma_database
      POSTGRES_USER: mma_user
      POSTGRES_PASSWORD: mma_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mma_user -d mma_database"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mma-network

  # Redis cache
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - mma-network

  # Development tools (optional)
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    networks:
      - mma-network

  # Redis Commander (optional)
  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - "8081:8081"
    environment:
      REDIS_HOSTS: local:redis:6379
    networks:
      - mma-network

volumes:
  postgres_data:
  redis_data:

networks:
  mma-network:
    driver: bridge