# Generated by Django 5.0.1 on 2025-07-29 07:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('abbreviation', models.CharField(max_length=10, unique=True)),
                ('founded_date', models.DateField(blank=True, null=True)),
                ('headquarters', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WeightClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('weight_limit_lbs', models.PositiveIntegerField()),
                ('weight_limit_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_classes', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Weight Class',
                'verbose_name_plural': 'Weight Classes',
                'db_table': 'weight_classes',
                'ordering': ['organization', 'weight_limit_kg'],
                'unique_together': {('organization', 'name', 'gender')},
            },
        ),
    ]
