# Generated by Django 5.0.1 on 2025-07-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weightclass",
            name="weight_limit_kg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="weightclass",
            name="weight_limit_lbs",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
