# Generated by Django 5.0.1 on 2025-07-29 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('fighters', '0002_fighthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighthistory',
            name='fight',
            field=models.ForeignKey(blank=True, help_text='Link to the authoritative Fight record (None for legacy data)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fighter_perspectives', to='events.fight'),
        ),
        migrations.AlterField(
            model_name='fighthistory',
            name='data_source',
            field=models.CharField(choices=[('wikipedia', 'Wikipedia'), ('manual', 'Manual Entry'), ('ufc_stats', 'UFC Stats'), ('sherdog', 'Sherdog'), ('tapology', 'Tapology'), ('ai_completion', 'AI Completion'), ('authoritative_fight', 'Generated from Fight Record'), ('reconciled', 'Reconciled with Fight Record')], default='wikipedia', max_length=50),
        ),
    ]
