# Generated by Django 5.0.1 on 2025-07-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fighters", "0010_add_pending_fighter"),
    ]

    operations = [
        migrations.AddField(
            model_name="fighter",
            name="json_import_data",
            field=models.TextField(
                blank=True,
                help_text="Paste complete fighter JSON here to automatically populate all fields and fight history. Data will be processed on save and this field will be cleared.",
            ),
        ),
    ]
