# Generated by Django 5.0.1 on 2025-07-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fighters", "0012_make_nickname_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fighter",
            name="nationality",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="pendingfighter",
            name="nationality",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
