# Generated by Django 5.0.1 on 2025-07-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fighters", "0013_make_nationality_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fighter",
            name="wikipedia_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
