# Generated by Django 5.0.1 on 2025-07-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fighters", "0014_make_wikipedia_url_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fighter",
            name="birth_first_name",
            field=models.CharField(
                blank=True,
                help_text="Legal first name at birth",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fighter",
            name="birth_last_name",
            field=models.CharField(
                blank=True,
                help_text="Legal last name at birth",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fighter",
            name="birth_place",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="fighter",
            name="fighting_out_of",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="fighter",
            name="profile_image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fighter",
            name="stance",
            field=models.CharField(
                blank=True,
                choices=[
                    ("orthodox", "Orthodox"),
                    ("southpaw", "Southpaw"),
                    ("switch", "Switch"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fighter",
            name="team",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="fighter",
            name="years_active",
            field=models.CharField(
                blank=True,
                help_text="e.g., '2010-present' or '2005-2018'",
                max_length=100,
                null=True,
            ),
        ),
    ]
