# Generated by Django 5.0.1 on 2025-07-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fighters", "0015_make_event_scraping_fields_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fighter",
            name="data_source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual Entry"),
                    ("wikipedia", "Wikipedia"),
                    ("ufc_stats", "UFC Stats"),
                    ("ai_completion", "AI Completion"),
                ],
                default="manual",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="fighthistory",
            name="data_source",
            field=models.CharField(
                choices=[
                    ("wikipedia", "Wikipedia"),
                    ("manual", "Manual Entry"),
                    ("ufc_stats", "UFC Stats"),
                    ("sherdog", "Sherdog"),
                    ("tapology", "Tapology"),
                    ("ai_completion", "AI Completion"),
                ],
                default="wikipedia",
                max_length=200,
            ),
        ),
    ]
