# Generated by Django 5.0.1 on 2025-07-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fighters", "0016_increase_data_source_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fighthistory",
            name="ending_time",
            field=models.CharField(
                blank=True,
                help_text="Time in round when fight ended (MM:SS format, supports long durations)",
                max_length=15,
            ),
        ),
    ]
