# Generated by Django 5.0.1 on 2025-07-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="featured_image",
            field=models.URLField(
                blank=True, help_text="Main article image URL (recommended: 1200x630px)"
            ),
        ),
    ]
